class CommonAudios:
    TO_ADD_OR_SUBTRACT_FRACTIONS_YOU_HAVE_TO_MAKE_THEM_HAVE_THE_SAME_DENOMINATOR = "Żeby dodać lub odjąć ułamki musimy sprawić by miały te same mianowniki."
    HOW_TO_ADD_FRACTIONS = "Cześć, pokażę Ci dzisiaj, jak dodawać ułamki."
    HOW_TO_SUBTRACT_FRACTIONS = "Cześć, pokażę Ci dzisiaj, jak odejmować ułamki."
    HOW_TO_MULTIPLY_FRACTIONS = "Cześć, pokażę Ci dzisiaj, jak mnożyć ułamki."
    HOW_TO_DIVIDE_FRACTIONS = "Cześć, pokażę Ci dzisiaj, jak dzielić ułamki."
    HOW_TO_SIMPLIFY_FRACTIONS = "Cześć, pokażę Ci dzisiaj, jak skracać ułamki."
    NEW_FRACTION = "W wyniku działania otrzymujemy nowy ułamek."
    MULTIPLICATION_IN_DENOMINATOR = "W mianowniku zapisujemy mnożenie mianowników."
    MULTIPLICATION_IN_NUMERATOR = "W liczniku zapisujemy mnożenie liczników."
    BUTTERFLY_MULTIPLICATION = "W liczniku zapisujemy licznik pierwszego ułamka pomnożony z mianownikiem drugiego ułamka oraz licznik drugiego ułamka pomnożony z mianownikiem pierwszego ułamka."
    WE_MULTIPLY = "Mnożymy."
    WE_ADD = "Dodajemy."
    WE_SUBTRACT = "Odejmujemy."
    WE_SIMPLIFY_FRACTION = "Skracamy ułamek."
    WE_CONVERT_DIVISION_TO_MULTIPLICATION = "Przekształcamy dzielenie przez ułamek na mnożenie z jego odwrotnością."
    WE_DIVIDE_NUMERATOR_AND_DENOMINATOR_BY_PRIMES = "Musimy dzielić licznik i mianownik przez kolejne liczby pierwsze."
    LOG_1 = "Logarytm o wartości logarytmowanej 1 zawsze przyjmuje wartość 0."
    FRAC_IN_LOG_DIVISION = "Wartością logarytmowaną jest ułamek. Rozdzielamy logarytm na różnicę logarytmu licznika i mianownika."
    HOW_TO_CALC_LOG = "Cześć, pokażę Ci dzisiaj, jak obliczać logarytmy. W pierwszym etapie musimy przekształcić wszystkie liczby złożone na ich czynniki pierwsze."
    ROOT2POWER = "Kolejnym krokiem jest zamiana pierwiastka na potęgę."
    EXP2NUMERATOR_AND_DENOMINATOR = (
        "Następnie przenosimy wykładnik z ułamka na licznik i mianownik."
    )
    EXP_MULTIPLICATION = "Upraszczamy potęgi poprzez mnożenie wykładników."
    THANKU = "Dziękuję za uwagę."
    NEXT_FRACTION_DIVISION = "Dalej równanie rozwiązuje się dzieleniem ułamków."
    NEGATIVE_EXP = "W tym wypadku mamy do czynienia z wykładnikami ujemnymi. Przekształcamy je na dodatnie odwracając ich podstawy."
    SAME_BASE_POWER_MUL = "W tym wypadku mamy do czynienia z mnożeniem potęg o tych samych podstawach więc możemy dodać ich wykładniki."
    LOG2LOG_FRAC = "W postawie logarytmu występuje liczba pierwsza podniesiona do potęgi. Przekształcamy logarytm na ułamek logarytmów."
    LOG2NUM = "Podstawa logarytmu ma tę samą wartość co podstawa liczby logarytmowanej. Przekształcamy logarytm na wykładnik liczby logarytmowanej."
